# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

def notIn(s1,s2):
  return [x for x in s2 if x not in s1][0]
  
s = "abcd"
t = "abcde"
# print(notIn(s,t))
